# Generated by Django 3.0.8 on 2020-07-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapi', '0002_auto_20200729_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='Dependants',
            new_name='Dependents',
        ),
    ]
